# Copyright(c) 2018 FUJITSU CORPORATION All Rights Reserved.
# @file        Makefile
# @brief       Make Configuration file
# @author      anhnguyen
# @date        2018/12/10

all:
	make -C mdbcommon/opt/FJSVmapdb
	make -C famsdatamanagement/opt/FJSVmapdb

clean:
	make -C mdbcommon/opt/FJSVmapdb clean
	make -C famsdatamanagement/opt/FJSVmapdb clean
